FROM ubuntu:22.04

#Install prereqyusites
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    sudo \
    openssh-client \
    git \
    python3 \
    python3-pip \
    sshpass && \
  pip3 install ansible && \
  useradd -ms /bin/bash ansible && \
  echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN mkdir -p /home/ansible/.ssh && chown ansible:ansible /home/ansible/.ssh

USER ansible
WORKDIR /home/ansible

CMD ["bash"]
